import type { Dare } from './types';

export const level4Dares: Dare[] = [
  { id: 'l4_1',  level: 4, tags: ['flirty', 'physical'], text: 'Give whoever spun you a soft kiss on the neck or collarbone.' },
  { id: 'l4_2',  level: 4, tags: ['bold', 'embarrassing'], text: 'Let the person to your left text "I think I\'m in love with you" to any single person in your phone.' },
  { id: 'l4_3',  level: 4, tags: ['physical', 'flirty'], text: 'Sit on the floor between someone\'s legs and let them massage your shoulders for 2 minutes.' },
  { id: 'l4_4',  level: 4, tags: ['bold', 'social'], text: 'Admit the most inappropriate or taboo thing you\'ve ever masturbated to.' },
  { id: 'l4_5',  level: 4, tags: ['flirty', 'challenge'], text: 'Take an ice cube, put it in your mouth, and pass it to the person of your choice using no hands.' },
  { id: 'l4_6',  level: 4, tags: ['alcohol', 'physical'], text: 'Take a body shot out of someone\'s belly button.' },
  { id: 'l4_7',  level: 4, tags: ['flirty', 'embarrassing'], text: 'Show the group the last nude or semi-nude photo you took of yourself.' },
  { id: 'l4_8',  level: 4, tags: ['physical', 'bold'], text: 'Remove your shirt or pants (your choice) for the next 3 rounds.' },
  { id: 'l4_9',  level: 4, tags: ['social', 'flirty'], text: 'Describe in detail what your "perfect" night of sex looks like.' },
  { id: 'l4_10', level: 4, tags: ['flirty', 'funny'], text: 'Give a 30-second seductive lap dance to the person across from you without breaking eye contact.' },
  { id: 'l4_11', level: 4, tags: ['bold', 'challenge'], text: 'Call an ex and leave a voicemail saying you had a dream about them.' },
  { id: 'l4_12', level: 4, tags: ['physical', 'flirty'], text: 'Let someone gently bite your inner thigh or stomach.' },
  { id: 'l4_13', level: 4, tags: ['embarrassing', 'social'], text: 'Tell the group about the worst or most awkward sexual encounter of your life.' },
  { id: 'l4_14', level: 4, tags: ['flirty', 'bold'], text: 'Who in the room has the best "vibe" in bed? Rank your top 3.' },
  { id: 'l4_15', level: 4, tags: ['physical', 'challenge'], text: 'Get blindfolded and have someone lightly trace an object over your body. Guess who is doing it.' },
  { id: 'l4_16', level: 4, tags: ['alcohol', 'flirty'], text: 'Drink someone else’s drink while they are holding the cup in their teeth.' },
  { id: 'l4_17', level: 4, tags: ['flirty', 'bold'], text: 'Have you ever slept with someone purely out of boredom? Details.' },
  { id: 'l4_18', level: 4, tags: ['physical', 'social'], text: 'Let two people of your choice take off your socks and shoes with only Their teeth.' },
  { id: 'l4_19', level: 4, tags: ['embarrassing', 'challenge'], text: 'Admit to an embarrassing search history related to intimacy.' },
  { id: 'l4_20', level: 4, tags: ['flirty', 'physical'], text: 'Let the person to your right run their hand up your leg, stopping wherever you decide.' },
  { id: 'l4_21', level: 4, tags: ['bold', 'social'], text: 'Have you ever hooked up with a co-worker or boss? Give the full story.' },
  { id: 'l4_22', level: 4, tags: ['physical', 'flirty'], text: 'Choose a partner. You must both eat a piece of food (like a gummy) from opposite ends until your lips touch.' },
  { id: 'l4_23', level: 4, tags: ['flirty', 'funny'], text: 'Fake a 10-second orgasm noise. If you laugh, take a shot.' },
  { id: 'l4_24', level: 4, tags: ['alcohol', 'bold'], text: 'Drink if you have ever hit on someone only to find out they were taken, but still kept flirting.' },
  { id: 'l4_25', level: 4, tags: ['flirty', 'embarrassing'], text: 'Read aloud the dirtiest text you’ve ever sent to someone.' },
  { id: 'l4_26', level: 4, tags: ['physical', 'social'], text: 'Let someone in the room blindfold you and feed you three drops of a mystery liquid from the kitchen.' },
  { id: 'l4_27', level: 4, tags: ['bold', 'flirty'], text: 'Admit if you have ever had romantic or sexual feelings for anyone in your immediate friend group.' },
  { id: 'l4_28', level: 4, tags: ['physical', 'challenge'], text: 'Take off your bra or binder underneath your clothes without removing your shirt. Keep it off.' },
  { id: 'l4_29', level: 4, tags: ['embarrassing', 'bold'], text: 'Show everyone the spiciest text thread currently sitting in your messages.' },
  { id: 'l4_30', level: 4, tags: ['flirty', 'physical'], text: 'Let someone run a feather, ice cube, or finger down the inside of your thigh.' },
  { id: 'l4_31', level: 4, tags: ['alcohol', 'flirty'], text: 'Take a shot off the collarbone of someone in the room.' },
  { id: 'l4_32', level: 4, tags: ['bold', 'challenge'], text: 'Message an old high school friend you haven’t spoken to in years saying "I can’t stop thinking about you".' },
  { id: 'l4_33', level: 4, tags: ['social', 'embarrassing'], text: 'Confess the most down-bad, desperate thing you’ve ever done for someone’s attention.' },
  { id: 'l4_34', level: 4, tags: ['physical', 'funny'], text: 'Let everyone in the room physically adjust your outfit to make you look as "slutty" as possible.' },
  { id: 'l4_35', level: 4, tags: ['flirty', 'bold'], text: 'What’s your biggest "red flag" kink?' },
  { id: 'l4_36', level: 4, tags: ['physical', 'challenge'], text: 'Let someone give you a wedgie or playfully smack your ass.' },
  { id: 'l4_37', level: 4, tags: ['bold', 'embarrassing'], text: 'Admit to a time you got caught doing something you shouldn’t have been doing.' },
  { id: 'l4_38', level: 4, tags: ['flirty', 'social'], text: 'Who do you think has the highest sex drive in the room?' },
  { id: 'l4_39', level: 4, tags: ['physical', 'flirty'], text: 'Kiss the person to your left anywhere on the face or neck for exactly 5 seconds.' },
  { id: 'l4_40', level: 4, tags: ['alcohol', 'bold'], text: 'If you have ever hooked up with an ex after you broke up, drink everything left in your cup.' },
  { id: 'l4_41', level: 4, tags: ['funny', 'embarrassing'], text: 'Describe what your "O-face" looks like to the best of your ability.' },
  { id: 'l4_42', level: 4, tags: ['bold', 'challenge'], text: 'Let someone DM the most attractive person you follow "You up?"' },
  { id: 'l4_43', level: 4, tags: ['flirty', 'social'], text: 'Who in the room is your "hall pass"?' },
  { id: 'l4_44', level: 4, tags: ['physical', 'funny'], text: 'Crawl across the room to a player of your choice while making intense eye contact.' },
  { id: 'l4_45', level: 4, tags: ['embarrassing', 'bold'], text: 'Show us the most embarrassing purchase you\'ve made on Amazon.' },
  { id: 'l4_46', level: 4, tags: ['flirty', 'challenge'], text: 'Whisper exactly what you want to do to someone in the room in their ear.' },
  { id: 'l4_47', level: 4, tags: ['alcohol', 'physical'], text: 'Lick salt off someone’s neck, take a shot of tequila, and take the lime from their mouth.' },
  { id: 'l4_48', level: 4, tags: ['bold', 'social'], text: 'What is the most unethical thing you’ve done out of jealousy?' },
  { id: 'l4_49', level: 4, tags: ['flirty', 'embarrassing'], text: 'What is the weirdest place you’ve ever sent or received a nude photo?' },
  { id: 'l4_50', level: 4, tags: ['physical', 'bold'], text: 'Let the person across from you lightly choke or grab your neck for 5 seconds.' },
  /* ── Batch 2 — Dares 51–80 ── */
  { id: 'l4_51', level: 4, tags: ['bold', 'social'], text: 'Confess the raunchiest dream you\'ve had about someone in this room. Every detail.' },
  { id: 'l4_52', level: 4, tags: ['physical', 'flirty'], text: 'Let someone in the room drag their bottom lip slowly across your collarbone.' },
  { id: 'l4_53', level: 4, tags: ['flirty', 'challenge'], text: 'Whisper the filthiest thing you\'d ever say to someone in their ear. They must keep a straight face.' },
  { id: 'l4_54', level: 4, tags: ['alcohol', 'physical'], text: 'Do a tequila sunrise shot where you hold the glass in someone else\'s teeth to pour it.' },
  { id: 'l4_55', level: 4, tags: ['bold', 'embarrassing'], text: 'Describe your exact bedroom personality using only three words. Vote if the room agrees.' },
  { id: 'l4_56', level: 4, tags: ['flirty', 'social'], text: 'Pick a person in the room and tell them, in detail, a scenario where things get out of hand between you two.' },
  { id: 'l4_57', level: 4, tags: ['physical', 'challenge'], text: 'Get on all fours for 30 seconds. Someone in the room gets to narrate dramatically.' },
  { id: 'l4_58', level: 4, tags: ['bold', 'funny'], text: 'Rank everyone in the room in order of who you\'d hook up with first to last. No ties.' },
  { id: 'l4_59', level: 4, tags: ['flirty', 'physical'], text: 'Trace your tongue across the back of the hand of the person to your left.' },
  { id: 'l4_60', level: 4, tags: ['social', 'bold'], text: 'Reveal the most embarrassing thing someone has said mid-intimacy to you.' },
  { id: 'l4_61', level: 4, tags: ['alcohol', 'bold'], text: 'Pour a shot. Drink it off your own body part of any choice without spilling.' },
  { id: 'l4_62', level: 4, tags: ['challenge', 'funny'], text: 'Pretend you\'re recording a 30-second adult-rated audio message for someone in the room.' },
  { id: 'l4_63', level: 4, tags: ['social', 'flirty'], text: 'Tell the room which person here has the most physically irresistible feature and be specific.' },
  { id: 'l4_64', level: 4, tags: ['physical', 'bold'], text: 'Remove one item of clothing of your choice right now and leave it off for 4 rounds.' },
  { id: 'l4_65', level: 4, tags: ['flirty', 'embarrassing'], text: 'Read the most suggestive message you\'ve ever drafted but never sent.' },
  { id: 'l4_66', level: 4, tags: ['bold', 'challenge'], text: 'Let the group collectively decide your next tinder/dating app bio. You must set it live.' },
  { id: 'l4_67', level: 4, tags: ['physical', 'flirty'], text: 'Put your head in the lap of the person to your left and stay there for two rounds.' },
  { id: 'l4_68', level: 4, tags: ['alcohol', 'social'], text: 'Take a shot if you\'ve sent an explicit photo while sober. Take two if you were drunk.' },
  { id: 'l4_69', level: 4, tags: ['embarrassing', 'bold'], text: 'Describe a sexual experience that still makes you cringe or laugh when you think about it.' },
  { id: 'l4_70', level: 4, tags: ['flirty', 'challenge'], text: 'Look the person across from you in the eye and describe what their hands could do in detail.' },
  { id: 'l4_71', level: 4, tags: ['bold', 'social'], text: 'What is the most depraved thought you\'ve had about someone you shouldn\'t have?' },
  { id: 'l4_72', level: 4, tags: ['physical', 'funny'], text: 'Let someone draw on your body with a marker anywhere above the waist. They choose the design.' },
  { id: 'l4_73', level: 4, tags: ['social', 'embarrassing'], text: 'Have you ever been recorded during intimacy — knowingly or unknowingly?' },
  { id: 'l4_74', level: 4, tags: ['flirty', 'bold'], text: 'Tell the one person in the room you\'re most attracted to exactly why they\'re attractive.' },
  { id: 'l4_75', level: 4, tags: ['alcohol', 'challenge'], text: 'Everyone who has participated in anything remotely kinky this year takes a full drink.' },
  { id: 'l4_76', level: 4, tags: ['social', 'bold'], text: 'If you could wake up next to anyone in this room tomorrow, who would it be and what would you hope happened?' },
  { id: 'l4_77', level: 4, tags: ['flirty', 'social'], text: 'Go around the room and rate each person\'s "intimacy energy" out of 10. Justify every score.' },
  { id: 'l4_78', level: 4, tags: ['physical', 'challenge'], text: 'Let someone use a piece of your own clothing to blindfold you, then guess who touches your face.' },
  { id: 'l4_79', level: 4, tags: ['embarrassing', 'bold'], text: 'What is something about your s*x life that would surprise everyone in this room?' },
  { id: 'l4_80', level: 4, tags: ['social', 'funny'], text: 'Name your signature move and demonstrate it on a willing participant in the room.' },
];
