import type { Dare } from './types';

export const level2Dares: Dare[] = [
  { id: 'l2_1',  level: 2, tags: ['flirty', 'social'], text: 'Sit on the lap of the person across from you for the next 2 turns.' },
  { id: 'l2_2',  level: 2, tags: ['embarrassing', 'bold'], text: 'Open your DMs on the app of your choice and read the most recent flirtatious conversation.' },
  { id: 'l2_3',  level: 2, tags: ['bold', 'challenge'], text: 'Let the person to your left post whatever they want on your social media story right now.' },
  { id: 'l2_4',  level: 2, tags: ['flirty', 'bold'], text: 'Confess what you think is the sexiest physical trait of the person picking the dare after you.' },
  { id: 'l2_5',  level: 2, tags: ['flirty', 'social'], text: 'Show the group how you lean in for a first kiss on a pillow. Everyone gets to judge your form.' },
  { id: 'l2_6',  level: 2, tags: ['alcohol', 'bold'], text: 'Drink someone else\'s drink — chosen by the group — no questions asked.' },
  { id: 'l2_7',  level: 2, tags: ['social', 'bold'], text: 'Rank the top 3 people in this room you would invite if you threw an adults-only party.' },
  { id: 'l2_8',  level: 2, tags: ['embarrassing', 'challenge'], text: 'Let the group choose a random contact in your phone. You must call them and hang up if they say hello.' },
  { id: 'l2_9',  level: 2, tags: ['funny', 'flirty'], text: 'Give a lap dance to a chair, treating it like it\'s the hottest person in the room for 30 seconds.' },
  { id: 'l2_10', level: 2, tags: ['bold', 'flirty'], text: 'Reveal a kink or fetish that you somewhat understand, even if you wouldn\'t try it.' },
  { id: 'l2_11', level: 2, tags: ['physical', 'flirty'], text: 'Let the person to your right feed you a piece of food or a sip of a drink without breaking eye contact.' },
  { id: 'l2_12', level: 2, tags: ['embarrassing', 'flirty'], text: 'Admit the most inappropriate place you have ever hooked up with someone or strongly considered.' },
  { id: 'l2_13', level: 2, tags: ['bold', 'challenge'], text: 'Let the person across from you send a 10 second voice note to anyone in your contacts.' },
  { id: 'l2_14', level: 2, tags: ['alcohol', 'physical'], text: 'Take a sip of your drink off the collarbone of someone in the group.' },
  { id: 'l2_15', level: 2, tags: ['embarrassing', 'bold'], text: 'Describe your absolute worst hookup or date in painful detail for 60 seconds.' },
  { id: 'l2_16', level: 2, tags: ['bold', 'embarrassing'], text: 'Let the group search a single suggestive word in your messages and read the top result.' },
  { id: 'l2_17', level: 2, tags: ['bold', 'flirty'], text: 'Whisper an actual dirty secret into the ear of the person to your left. They cannot repeat it.' },
  { id: 'l2_18', level: 2, tags: ['flirty', 'social'], text: 'Tell the group exactly what turns you on most in a partner physically.' },
  { id: 'l2_19', level: 2, tags: ['flirty', 'physical'], text: 'Remove one article of clothing in a seductive manner. (Socks, jackets, belts count!)' },
  { id: 'l2_20', level: 2, tags: ['alcohol', 'challenge'], text: 'Let someone in the group mix you a "mystery shot" using anything drinkable in the kitchen. You must take it.' },
  { id: 'l2_21', level: 2, tags: ['flirty', 'social'], text: 'Whose bed in this room would you most likely sneak into? Point to them.' },
  { id: 'l2_22', level: 2, tags: ['embarrassing', 'funny'], text: 'Show off the most questionable photo in your "Recently Deleted" album.' },
  { id: 'l2_23', level: 2, tags: ['alcohol', 'social'], text: 'Everyone who has ever sent a risky text while drunk has to drink. If you have, take two drinks.' },
  { id: 'l2_24', level: 2, tags: ['bold', 'social'], text: 'Admit your toxic trait in relationships.' },
  { id: 'l2_25', level: 2, tags: ['flirty', 'physical'], text: 'Let the group lightly trace their fingers down your arm and spine for 15 seconds while you close your eyes.' },
  { id: 'l2_26', level: 2, tags: ['bold', 'embarrassing'], text: 'Open your private notes app and read a random thought aloud.' },
  { id: 'l2_27', level: 2, tags: ['physical', 'challenge'], text: 'Hold hands with the person next to you for the rest of the round.' },
  { id: 'l2_28', level: 2, tags: ['social', 'flirty'], text: 'Describe your perfect "friends with benefits" scenario without using names.' },
  { id: 'l2_29', level: 2, tags: ['flirty', 'social'], text: 'Who strikes you as the freak of the group? Why?' },
  { id: 'l2_30', level: 2, tags: ['alcohol', 'bold'], text: 'Drink if you\'ve ever lied about your "number".' },
  { id: 'l2_31', level: 2, tags: ['physical', 'funny'], text: 'Give someone a fast and chaotic 20-second back massage.' },
  { id: 'l2_32', level: 2, tags: ['flirty', 'bold'], text: 'Show everyone the last person you matched with on a dating app. If you don\'t have one, show your ex.' },
  { id: 'l2_33', level: 2, tags: ['social', 'funny'], text: 'What is a lie you told to get out of seeing someone recently?' },
  { id: 'l2_34', level: 2, tags: ['bold', 'flirty'], text: 'Name a celebrity you would ruin your life for.' },
  { id: 'l2_35', level: 2, tags: ['embarrassing', 'social'], text: 'What is the dumbest reason you\'ve ever cried over someone?' },
  { id: 'l2_36', level: 2, tags: ['creative', 'flirty'], text: 'Describe a romantic scene starring you and the person to your right.' },
  { id: 'l2_37', level: 2, tags: ['alcohol', 'flirty'], text: 'Pick a partner. You both have to sip from the exact same cup at the exact same time without spilling.' },
  { id: 'l2_38', level: 2, tags: ['physical', 'challenge'], text: 'Let the person across from you draw something small on your face with a marker.' },
  { id: 'l2_39', level: 2, tags: ['social', 'flirty'], text: 'Have you ever had a dream about someone in this room? Drink if you refuse to answer.' },
  { id: 'l2_40', level: 2, tags: ['embarrassing', 'funny'], text: 'Show the group standard photos you keep in your "hidden folder" (PG-13 only).' },
  { id: 'l2_41', level: 2, tags: ['challenge', 'bold'], text: 'Let the person to your left text a heart emoji to anyone they want in your phone.' },
  { id: 'l2_42', level: 2, tags: ['flirty', 'social'], text: 'What is the most attractive non-physical quality in a partner?' },
  { id: 'l2_43', level: 2, tags: ['alcohol', 'bold'], text: 'Drink if you have ever kissed someone in a public place.' },
  { id: 'l2_44', level: 2, tags: ['flirty', 'physical'], text: 'Rest your head on someone’s shoulder for the next 2 turns.' },
  { id: 'l2_45', level: 2, tags: ['social', 'bold'], text: 'If you could read one person’s mind in this room, who would it be?' },
  { id: 'l2_46', level: 2, tags: ['embarrassing', 'funny'], text: 'Reveal a guilty pleasure movie or song you pretend not to like.' },
  { id: 'l2_47', level: 2, tags: ['flirty', 'social'], text: 'Who here would you most want to go on a spontaneous road trip with?' },
  { id: 'l2_48', level: 2, tags: ['bold', 'embarrassing'], text: 'Admit to the biggest rumor you have heard about someone in this room. Drink twice if you don\'t speak.' },
  { id: 'l2_49', level: 2, tags: ['funny', 'challenge'], text: 'Seductively eat whatever snack is closest to you.' },
  { id: 'l2_50', level: 2, tags: ['social', 'flirty'], text: 'Who do you think has the highest body count in this room?' },
  /* ── Batch 2 — Dares 51–80 ── */
  { id: 'l2_51', level: 2, tags: ['bold', 'social'], text: 'Tell the group the wildest place you\'ve ever hooked up or made out with someone.' },
  { id: 'l2_52', level: 2, tags: ['flirty', 'embarrassing'], text: 'What is the most embarrassing thing you have done to get someone\'s attention on a date?' },
  { id: 'l2_53', level: 2, tags: ['social', 'bold'], text: 'Name someone you would sleep with for a million dollars. Now name someone you would sleep with for free.' },
  { id: 'l2_54', level: 2, tags: ['alcohol', 'challenge'], text: 'Shotgun a drink or take 3 large sips in a row. No stopping.' },
  { id: 'l2_55', level: 2, tags: ['physical', 'flirty'], text: 'Sit in the lap of the person of your choice for the next full round.' },
  { id: 'l2_56', level: 2, tags: ['bold', 'embarrassing'], text: 'What is the shadiest thing you have done to keep someone interested in you?' },
  { id: 'l2_57', level: 2, tags: ['flirty', 'social'], text: 'Tell the person to your left what you first noticed about them when you met them — honestly.' },
  { id: 'l2_58', level: 2, tags: ['challenge', 'funny'], text: 'Describe the contents of your bedside drawer without lying. Group asks clarifying questions.' },
  { id: 'l2_59', level: 2, tags: ['social', 'bold'], text: 'Tell the room something you\'ve done that you\'ve never confessed to anyone before.' },
  { id: 'l2_60', level: 2, tags: ['flirty', 'physical'], text: 'Give the person who spun you a lingering 30-second shoulder massage.' },
  { id: 'l2_61', level: 2, tags: ['alcohol', 'social'], text: 'Everyone drinks once for every person in this room you\'ve considered romantically at any point.' },
  { id: 'l2_62', level: 2, tags: ['bold', 'funny'], text: 'What is your most chaotic "it made sense at the time" decision you\'ve made in a relationship?' },
  { id: 'l2_63', level: 2, tags: ['social', 'flirty'], text: 'Give a brutally honest compliment to every person in the room in 60 seconds flat.' },
  { id: 'l2_64', level: 2, tags: ['embarrassing', 'bold'], text: 'Read the most recent search in your browser\'s incognito history. Time\'s up in 5 seconds.' },
  { id: 'l2_65', level: 2, tags: ['physical', 'challenge'], text: 'Let the group blindfold you and feed you something from the kitchen. You must finish it.' },
  { id: 'l2_66', level: 2, tags: ['flirty', 'creative'], text: 'Write a one-sentence dirty poem about the person to your left. Read it aloud.' },
  { id: 'l2_67', level: 2, tags: ['social', 'bold'], text: 'Who in this room has a quality that would make them an amazing partner that most people don\'t notice?' },
  { id: 'l2_68', level: 2, tags: ['alcohol', 'flirty'], text: 'Take a shot off the wrist of someone you choose in the room.' },
  { id: 'l2_69', level: 2, tags: ['embarrassing', 'funny'], text: 'Rate yourself as a kisser out of 10 based on actual feedback you have received.' },
  { id: 'l2_70', level: 2, tags: ['social', 'flirty'], text: 'Tell the room the most blatant lie you have ever told on a first date.' },
  { id: 'l2_71', level: 2, tags: ['bold', 'challenge'], text: 'Let the group pick a contact from your phone. You must send them "Hey stranger" right now.' },
  { id: 'l2_72', level: 2, tags: ['physical', 'funny'], text: 'Impersonate how you think each person in this room kisses. Be theatrical.' },
  { id: 'l2_73', level: 2, tags: ['social', 'embarrassing'], text: 'What was your most desperate act to make someone like you back?' },
  { id: 'l2_74', level: 2, tags: ['flirty', 'bold'], text: 'Describe your ideal type in full detail — looks, personality, and one surprising requirement.' },
  { id: 'l2_75', level: 2, tags: ['alcohol', 'challenge'], text: 'Chug your current drink for 5 full seconds without stopping.' },
  { id: 'l2_76', level: 2, tags: ['social', 'bold'], text: 'Confess the nastiest thing you have ever said about someone behind their back.' },
  { id: 'l2_77', level: 2, tags: ['flirty', 'social'], text: 'If someone said they had a crush on you right now, which person in this room would you most want it to be?' },
  { id: 'l2_78', level: 2, tags: ['physical', 'challenge'], text: 'Let the person to your right apply lipstick or lip balm for you without using a mirror.' },
  { id: 'l2_79', level: 2, tags: ['embarrassing', 'bold'], text: 'Read the most embarrassing paragraph from your notes app out loud.' },
  { id: 'l2_80', level: 2, tags: ['social', 'funny'], text: 'Propose a toast that simultaneously roasts and praises every single person at the table.' },
];
