import type { Dare } from './types';

export const level1Dares: Dare[] = [
  { id: 'l1_1',  level: 1, tags: ['social', 'funny'], text: 'Give whoever spun you a new, slightly insulting nickname. Everyone must call them that for the next 10 minutes.' },
  { id: 'l1_2',  level: 1, tags: ['social', 'embarrassing'], text: 'Show everyone the last photo you saved to your camera roll that isn\'t a screenshot.' },
  { id: 'l1_3',  level: 1, tags: ['social', 'bold'], text: 'Explain your most controversial opinion about dating or relationships in exactly 30 seconds.' },
  { id: 'l1_4',  level: 1, tags: ['challenge', 'social'], text: 'Stare into the eyes of the person to your left for 15 seconds without blinking or smiling.' },
  { id: 'l1_5',  level: 1, tags: ['alcohol', 'social'], text: 'Pick someone in the room to finish your drink for you. If empty, you buy/make them their next one.' },
  { id: 'l1_6',  level: 1, tags: ['embarrassing', 'social'], text: 'Show the group the last three people you stalked on Instagram/TikTok.' },
  { id: 'l1_7',  level: 1, tags: ['social', 'bold'], text: 'Name the one person in this room you would actually trust to help you hide a body.' },
  { id: 'l1_8',  level: 1, tags: ['funny', 'social'], text: 'Do your best impression of the person to your right. They get to grade you.' },
  { id: 'l1_9',  level: 1, tags: ['flirty', 'social'], text: 'Rate the outfit of the person across from you out of 10 and give a shady fashion critique.' },
  { id: 'l1_10', level: 1, tags: ['alcohol', 'social'], text: 'Cheers! Everyone who has hooked up this month takes a drink. You drink twice.' },
  { id: 'l1_11', level: 1, tags: ['social', 'funny'], text: 'Describe the plot of your favorite movie in the most boring way possible.' },
  { id: 'l1_12', level: 1, tags: ['embarrassing', 'social'], text: 'Show the last TikTok/Reel you sent to someone.' },
  { id: 'l1_13', level: 1, tags: ['social', 'bold'], text: 'If you had to set up two people in this room on a blind date, who would it be?' },
  { id: 'l1_14', level: 1, tags: ['challenge', 'funny'], text: 'Speak only in a terrible British accent until it\'s your turn again.' },
  { id: 'l1_15', level: 1, tags: ['social', 'flirty'], text: 'Who in the room has the best "bedroom eyes"? Point to them.' },
  { id: 'l1_16', level: 1, tags: ['social', 'funny'], text: 'Let the person to your left rename you in their phone contacts right now.' },
  { id: 'l1_17', level: 1, tags: ['embarrassing', 'social'], text: 'What is the most embarrassing song on your current playlist? Play 10 seconds of it.' },
  { id: 'l1_18', level: 1, tags: ['alcohol', 'challenge'], text: 'Take a sip of your drink without using your hands.' },
  { id: 'l1_19', level: 1, tags: ['social', 'creative'], text: 'Give a 30-second Ted Talk about why ghosting is actually an acceptable practice.' },
  { id: 'l1_20', level: 1, tags: ['funny', 'embarrassing'], text: 'Show us the last text you received from a family member.' },
  { id: 'l1_21', level: 1, tags: ['social', 'bold'], text: 'Confess what your first impression was of the person who spun you.' },
  { id: 'l1_22', level: 1, tags: ['challenge', 'physical'], text: 'Balance something on your head for the next 3 turns.' },
  { id: 'l1_23', level: 1, tags: ['social', 'funny'], text: 'If someone handed you the aux cord right now, what song would you play to ruin the vibe?' },
  { id: 'l1_24', level: 1, tags: ['flirty', 'social'], text: 'Who in this room is definitely a "texting terrorist"? Call them out.' },
  { id: 'l1_25', level: 1, tags: ['bold', 'social'], text: 'What is a dealbreaker that you know is completely unreasonable, but you strictly enforce?' },
  { id: 'l1_26', level: 1, tags: ['funny', 'creative'], text: 'Act out the most ridiculous TikTok trend. If you refuse, drink.' },
  { id: 'l1_27', level: 1, tags: ['social', 'embarrassing'], text: 'Show the group the last Google search you made on your phone.' },
  { id: 'l1_28', level: 1, tags: ['flirty', 'social'], text: 'Pick someone in the room who looks like they would ruin your life.' },
  { id: 'l1_29', level: 1, tags: ['alcohol', 'funny'], text: 'Toast to the person in the room who is definitely going to cause a scene tonight. Everyone drinks.' },
  { id: 'l1_30', level: 1, tags: ['social', 'bold'], text: 'Admit to a petty crime or minor lie you told this week.' },
  { id: 'l1_31', level: 1, tags: ['challenge', 'funny'], text: 'Try to make the person across from you laugh without speaking.' },
  { id: 'l1_32', level: 1, tags: ['social', 'flirty'], text: 'Who has the best voice in the room? Give them a compliment.' },
  { id: 'l1_33', level: 1, tags: ['embarrassing', 'funny'], text: 'Tell the story of your most awkward encounter with a teacher/boss.' },
  { id: 'l1_34', level: 1, tags: ['social', 'bold'], text: 'If you had to be handcuffed to someone in this room for 24 hours, who would it be and why?' },
  { id: 'l1_35', level: 1, tags: ['creative', 'funny'], text: 'Pitch a terrible reality TV show concept featuring everyone in the room.' },
  { id: 'l1_36', level: 1, tags: ['alcohol', 'social'], text: 'Take a drink if you have ever stalked someone\'s ex on social media.' },
  { id: 'l1_37', level: 1, tags: ['social', 'embarrassing'], text: 'Read the draft of an unsent text on your phone.' },
  { id: 'l1_38', level: 1, tags: ['challenge', 'physical'], text: 'Do 5 squats while maintaining eye contact with the person to your left.' },
  { id: 'l1_39', level: 1, tags: ['social', 'flirty'], text: 'Compliment the person to your right using a cheesy pick-up line. If they cringe, you drink.' },
  { id: 'l1_40', level: 1, tags: ['bold', 'social'], text: 'What is the most hypocritical thing you constantly judge other people for?' },
  { id: 'l1_41', level: 1, tags: ['funny', 'embarrassing'], text: 'Describe the worst haircut or fashion phase you ever went through.' },
  { id: 'l1_42', level: 1, tags: ['social', 'challenge'], text: 'You can only answer questions with another question until it is your turn again.' },
  { id: 'l1_43', level: 1, tags: ['alcohol', 'flirty'], text: 'Make eye contact with someone and take a slow sip of your drink. If they look away, they drink.' },
  { id: 'l1_44', level: 1, tags: ['social', 'bold'], text: 'If someone gave you $50,000 to drop a friend, would you do it? Who?' },
  { id: 'l1_45', level: 1, tags: ['creative', 'funny'], text: 'Come up with a custom signature drink for the person who spun you and describe what\'s in it.' },
  { id: 'l1_46', level: 1, tags: ['embarrassing', 'social'], text: 'What is the most useless thing you have spent money on recently?' },
  { id: 'l1_47', level: 1, tags: ['social', 'flirty'], text: 'Who in the room is most likely to end up on reality TV? Why?' },
  { id: 'l1_48', level: 1, tags: ['challenge', 'physical'], text: 'Hold your breath for as long as you can while someone tells a joke. If you laugh/exhale, you fail.' },
  { id: 'l1_49', level: 1, tags: ['bold', 'social'], text: 'What is the absolute worst advice you\'ve ever given someone?' },
  { id: 'l1_50', level: 1, tags: ['funny', 'embarrassing'], text: 'Let the person to your right write a status update on your social media (they have 1 min to post it).' },
  /* ── Batch 2 — Dares 51–80 ── */
  { id: 'l1_51', level: 1, tags: ['social', 'bold'], text: 'Tell everyone the last time you cried and what caused it.' },
  { id: 'l1_52', level: 1, tags: ['funny', 'social'], text: 'Attempt a runway walk across the room while the group critiques your technique.' },
  { id: 'l1_53', level: 1, tags: ['embarrassing', 'social'], text: 'Share the most cringe comment you have left on someone\'s social media.' },
  { id: 'l1_54', level: 1, tags: ['creative', 'challenge'], text: 'Freestyle rap for 20 seconds using the names of everyone in this room.' },
  { id: 'l1_55', level: 1, tags: ['social', 'flirty'], text: 'Who in the room has the most kissable lips? Say it publicly.' },
  { id: 'l1_56', level: 1, tags: ['alcohol', 'social'], text: 'Take a drink for every year older you are than the youngest person in the room.' },
  { id: 'l1_57', level: 1, tags: ['bold', 'social'], text: 'Tell the group one thing you\'ve never admitted to a partner.' },
  { id: 'l1_58', level: 1, tags: ['funny', 'challenge'], text: 'Try to lick your elbow for 20 seconds. If you can\'t, you drink.' },
  { id: 'l1_59', level: 1, tags: ['social', 'embarrassing'], text: 'Show the group the most recent photo you took of yourself that is NOT a selfie.' },
  { id: 'l1_60', level: 1, tags: ['flirty', 'social'], text: 'Give the person across from you a genuine, slightly too-personal compliment.' },
  { id: 'l1_61', level: 1, tags: ['challenge', 'physical'], text: 'Do your best worm dance move right now. Group votes thumbs up or thumbs down.' },
  { id: 'l1_62', level: 1, tags: ['social', 'bold'], text: 'What is your most embarrassing celebrity crush that you\'ve never admitted publicly?' },
  { id: 'l1_63', level: 1, tags: ['alcohol', 'funny'], text: 'The person to your left decides your next drink order. You must finish it.' },
  { id: 'l1_64', level: 1, tags: ['creative', 'funny'], text: 'Write a one-sentence horror story using the full names of two people in this room.' },
  { id: 'l1_65', level: 1, tags: ['social', 'embarrassing'], text: 'Tell everyone what your love language is and whether you\'re actually honest about needing it.' },
  { id: 'l1_66', level: 1, tags: ['funny', 'social'], text: 'Explain why you specifically deserve to be on a reality dating show. Pitch yourself like a product.' },
  { id: 'l1_67', level: 1, tags: ['social', 'flirty'], text: 'Rank everyone in the room from most to least likely to be a secret hopeless romantic.' },
  { id: 'l1_68', level: 1, tags: ['challenge', 'funny'], text: 'Talk like a valley girl for the next two rounds or take one drink.' },
  { id: 'l1_69', level: 1, tags: ['social', 'bold'], text: 'What was the last lie you told to someone in this room? Confess it now.' },
  { id: 'l1_70', level: 1, tags: ['embarrassing', 'social'], text: 'What app do you always close before someone borrows your phone?' },
  { id: 'l1_71', level: 1, tags: ['social', 'funny'], text: 'Describe the most dramatic thing that has happened in your friend group in the last 3 months.' },
  { id: 'l1_72', level: 1, tags: ['creative', 'social'], text: 'Assign everyone in the room a Hogwarts house and briefly explain why.' },
  { id: 'l1_73', level: 1, tags: ['flirty', 'challenge'], text: 'Who here do you think would be the most chaotic to date? Say it out loud with reasons.' },
  { id: 'l1_74', level: 1, tags: ['alcohol', 'social'], text: 'Take a drink for every ex you still follow on social media right now.' },
  { id: 'l1_75', level: 1, tags: ['bold', 'social'], text: 'Tell the room about the most embarrassing thing you have done to impress a crush.' },
  { id: 'l1_76', level: 1, tags: ['funny', 'creative'], text: 'Do a 15-second stand-up set based on the funniest thing that happened this week.' },
  { id: 'l1_77', level: 1, tags: ['social', 'embarrassing'], text: 'Who in this room have you accidentally pocket-dialed or butt-texted? Tell the story.' },
  { id: 'l1_78', level: 1, tags: ['flirty', 'social'], text: 'Give the person to your right a totally unnecessary but oddly specific compliment.' },
  { id: 'l1_79', level: 1, tags: ['social', 'bold'], text: 'What is the most annoying habit you have in relationships that you refuse to change?' },
  { id: 'l1_80', level: 1, tags: ['funny', 'challenge'], text: 'Do your best celebrity impression and have the group guess who it is within 15 seconds.' },
];
