import type { Dare } from './types';

export const level3Dares: Dare[] = [
  { id: 'l3_1',  level: 3, tags: ['flirty', 'bold'], text: 'Tell the group exactly what you do when you want to heavily hit on someone.' },
  { id: 'l3_2',  level: 3, tags: ['physical', 'flirty'], text: 'Let the person to your right run their hands through your hair slowly for 30 seconds.' },
  { id: 'l3_3',  level: 3, tags: ['alcohol', 'bold'], text: 'Take a body shot off the stomach or chest of someone in the room. They choose who.' },
  { id: 'l3_4',  level: 3, tags: ['flirty', 'physical'], text: 'Demonstrate your favorite kissing technique on your hand or a pillow.' },
  { id: 'l3_5',  level: 3, tags: ['bold', 'embarrassing'], text: 'Read the spiciest text you\'ve ever received out loud to the group.' },
  { id: 'l3_6',  level: 3, tags: ['flirty', 'challenge'], text: 'Gently bite the earlobe or neck of the person across from you.' },
  { id: 'l3_7',  level: 3, tags: ['social', 'bold'], text: 'Rank everyone in the room based on how good in bed you think they are.' },
  { id: 'l3_8',  level: 3, tags: ['physical', 'bold'], text: 'Let the group strip you of two non-essential items of clothing.' },
  { id: 'l3_9',  level: 3, tags: ['flirty', 'social'], text: 'Who in the room do you secretly find incredibly attractive? Now is the time to confess.' },
  { id: 'l3_10', level: 3, tags: ['alcohol', 'flirty'], text: 'Drink intimately with another person (arms linked together) and lock eyes the whole time.' },
  { id: 'l3_11', level: 3, tags: ['bold', 'embarrassing'], text: 'Show the group the last "NSFW" photo or video you saved.' },
  { id: 'l3_12', level: 3, tags: ['flirty', 'physical'], text: 'Give a 1-minute massage to the person of your choice. You must use lotion if available.' },
  { id: 'l3_13', level: 3, tags: ['social', 'bold'], text: 'What is the most scandalous rumor you ever started or participated in spreading?' },
  { id: 'l3_14', level: 3, tags: ['challenge', 'physical'], text: 'Hold a plank position over someone lying on the floor for 30 seconds.' },
  { id: 'l3_15', level: 3, tags: ['flirty', 'funny'], text: 'Describe in detail exactly how you lost your virginity.' },
  { id: 'l3_16', level: 3, tags: ['alcohol', 'social'], text: 'Take a sip of your drink for every person in the room you would hypothetically hook up with.' },
  { id: 'l3_17', level: 3, tags: ['embarrassing', 'bold'], text: 'Let the person to your left go through the photos on your phone for 1 full minute. No hiding.' },
  { id: 'l3_18', level: 3, tags: ['flirty', 'physical'], text: 'Kiss someone in the room on a spot of their choosing (PG-13 limit).' },
  { id: 'l3_19', level: 3, tags: ['bold', 'social'], text: 'Admit to a time you were completely unfaithful or almost unfaithful.' },
  { id: 'l3_20', level: 3, tags: ['challenge', 'physical'], text: 'Let the group draw a fake tattoo anywhere they want on your body with a pen/marker.' },
  { id: 'l3_21', level: 3, tags: ['flirty', 'social'], text: 'Have you ever sent nudes to someone in this room or to an ex? If so, drink.' },
  { id: 'l3_22', level: 3, tags: ['embarrassing', 'funny'], text: 'Show us the most desperate, double-text you\'ve ever sent someone you liked.' },
  { id: 'l3_23', level: 3, tags: ['alcohol', 'bold'], text: 'Drink if you have ever had a one-night stand whose name you forgot.' },
  { id: 'l3_24', level: 3, tags: ['physical', 'flirty'], text: 'Whisper "You look so good right now" into the ear of the person across from you and hold eye contact.' },
  { id: 'l3_25', level: 3, tags: ['bold', 'challenge'], text: 'Send an "I miss you" text to an ex. You cannot explain until tomorrow.' },
  { id: 'l3_26', level: 3, tags: ['flirty', 'social'], text: 'Who has the best body in this room? Be honest.' },
  { id: 'l3_27', level: 3, tags: ['embarrassing', 'bold'], text: 'Describe the worst romantic rejection you have ever faced.' },
  { id: 'l3_28', level: 3, tags: ['physical', 'funny'], text: 'Let someone feed you a piece of food using only their mouth (Lady and the Tramp style, no kiss required).' },
  { id: 'l3_29', level: 3, tags: ['flirty', 'social'], text: 'Share your most successful "move" that almost never fails.' },
  { id: 'l3_30', level: 3, tags: ['alcohol', 'challenge'], text: 'Take a shot with no chaser and keep a completely straight face.' },
  { id: 'l3_31', level: 3, tags: ['bold', 'embarrassing'], text: 'What is the most illegal thing you\'ve ever done for fun or love?' },
  { id: 'l3_32', level: 3, tags: ['flirty', 'physical'], text: 'Trace the jawline of the person to your left with your fingertip.' },
  { id: 'l3_33', level: 3, tags: ['social', 'bold'], text: 'Have you ever had a crush on a friend’s significant other? Tell the story.' },
  { id: 'l3_34', level: 3, tags: ['funny', 'embarrassing'], text: 'Act out the face you make during "climax." If you refuse, drink your entire drink.' },
  { id: 'l3_35', level: 3, tags: ['flirty', 'challenge'], text: 'Stare intensely at someone\'s lips for 30 seconds without saying a word.' },
  { id: 'l3_36', level: 3, tags: ['alcohol', 'social'], text: 'Everyone who has ever faked reaching climax takes a drink.' },
  { id: 'l3_37', level: 3, tags: ['embarrassing', 'bold'], text: 'Openly share the most embarrassing fantasy you have.' },
  { id: 'l3_38', level: 3, tags: ['physical', 'flirty'], text: 'Let someone sit on your lap facing you for the next two rounds.' },
  { id: 'l3_39', level: 3, tags: ['challenge', 'bold'], text: 'Let someone search the word "naked" or "babe" in your texts and read the first result.' },
  { id: 'l3_40', level: 3, tags: ['flirty', 'social'], text: 'Tell the group what feature instantly gets you turned on.' },
  { id: 'l3_41', level: 3, tags: ['social', 'embarrassing'], text: 'Have you ever been caught in the act? Give details.' },
  { id: 'l3_42', level: 3, tags: ['physical', 'funny'], text: 'Put an ice cube down your shirt/pants and let it melt.' },
  { id: 'l3_43', level: 3, tags: ['alcohol', 'bold'], text: 'If you have had more than 5 drinks tonight, you must distribute 5 sips among players.' },
  { id: 'l3_44', level: 3, tags: ['flirty', 'bold'], text: 'Honestly rate your own kissing ability out of 10 and justify your score.' },
  { id: 'l3_45', level: 3, tags: ['bold', 'challenge'], text: 'Post a mildly suggestive blurry selfie to your stories right now.' },
  { id: 'l3_46', level: 3, tags: ['social', 'flirty'], text: 'Who would you most likely have a purely physical arrangement with in this room?' },
  { id: 'l3_47', level: 3, tags: ['embarrassing', 'funny'], text: 'What’s the most questionable thing you’ve Googled in incognito mode recently?' },
  { id: 'l3_48', level: 3, tags: ['physical', 'challenge'], text: 'Let the person across from you tie your hands together with a belt or shoelace for 1 turn.' },
  { id: 'l3_49', level: 3, tags: ['bold', 'social'], text: 'What is the most savage reason you ever broke up with someone?' },
  { id: 'l3_50', level: 3, tags: ['flirty', 'alcohol'], text: 'Have someone pour a shot while maintaining direct eye contact with you. Then take it.' },
  /* ── Batch 2 — Dares 51–80 ── */
  { id: 'l3_51', level: 3, tags: ['flirty', 'bold'], text: 'Describe in detail what you would do if you and the person to your left were alone for one hour.' },
  { id: 'l3_52', level: 3, tags: ['physical', 'challenge'], text: 'Let the person of your choice pin you against the wall for 5 seconds. No words allowed.' },
  { id: 'l3_53', level: 3, tags: ['bold', 'social'], text: 'What is the most messed-up thing you have ever done in the name of attraction?' },
  { id: 'l3_54', level: 3, tags: ['flirty', 'funny'], text: 'Roleplay a first date with the person across from you for 60 seconds. Go.' },
  { id: 'l3_55', level: 3, tags: ['alcohol', 'physical'], text: 'Take a shot off the top of someone\'s hand in the most seductive way you can manage.' },
  { id: 'l3_56', level: 3, tags: ['bold', 'embarrassing'], text: 'Tell the group the longest you\'ve ever gone without sex and what caused that drought.' },
  { id: 'l3_57', level: 3, tags: ['flirty', 'physical'], text: 'Bite your lip and hold intense eye contact with the person across from you for 15 full seconds.' },
  { id: 'l3_58', level: 3, tags: ['challenge', 'funny'], text: 'Reenact the dirtiest scene from any movie you\'ve seen. You must pick a co-star from the room.' },
  { id: 'l3_59', level: 3, tags: ['social', 'bold'], text: 'Tell the room about the most morally questionable thing you\'ve ever done romantically.' },
  { id: 'l3_60', level: 3, tags: ['flirty', 'social'], text: 'Go around the room and whisper something genuinely provocative to each person.' },
  { id: 'l3_61', level: 3, tags: ['alcohol', 'challenge'], text: 'Everyone takes a shot for every base you\'ve confirmed reaching this month.' },
  { id: 'l3_62', level: 3, tags: ['bold', 'funny'], text: 'Describe exactly how you would seduce someone if you had 10 minutes alone with them.' },
  { id: 'l3_63', level: 3, tags: ['social', 'flirty'], text: 'Based on vibes alone, who in this room do you think is the most adventurous in bed?' },
  { id: 'l3_64', level: 3, tags: ['embarrassing', 'bold'], text: 'Admit to a kink you thought you didn\'t have until you unexpectedly discovered you did.' },
  { id: 'l3_65', level: 3, tags: ['physical', 'challenge'], text: 'Let someone pour a little alcohol on your collarbone. They can choose how to get it off.' },
  { id: 'l3_66', level: 3, tags: ['flirty', 'creative'], text: 'Send what the group decides is the most suggestive but deniable text to an ex-flame. Right now.' },
  { id: 'l3_67', level: 3, tags: ['social', 'bold'], text: 'Tell the room who among your friends you think talks the most during sex.' },
  { id: 'l3_68', level: 3, tags: ['alcohol', 'flirty'], text: 'Everyone drinks for every day this week you thought about someone in this room romantically.' },
  { id: 'l3_69', level: 3, tags: ['embarrassing', 'funny'], text: 'Describe what your nickname would be if it was based on your worst sexual habit.' },
  { id: 'l3_70', level: 3, tags: ['social', 'flirty'], text: 'Who in this room would you most want to give or receive a lap dance from?' },
  { id: 'l3_71', level: 3, tags: ['bold', 'challenge'], text: 'Open Spotify and play the song that best represents your sex life. No edits.' },
  { id: 'l3_72', level: 3, tags: ['physical', 'funny'], text: 'Pretend you\'re filming a cologne/perfume ad. You have 30 seconds. Sell yourself like luxury.' },
  { id: 'l3_73', level: 3, tags: ['social', 'embarrassing'], text: 'Have you ever been rejected after initiating a kiss? Describe how it went.' },
  { id: 'l3_74', level: 3, tags: ['flirty', 'bold'], text: 'Tell the person to your right exactly what physical feature of theirs you noticed first.' },
  { id: 'l3_75', level: 3, tags: ['alcohol', 'challenge'], text: 'Take a drink every time someone in the group names a thing you would definitely do in bed.' },
  { id: 'l3_76', level: 3, tags: ['social', 'bold'], text: 'Confess the most desperate or unhinged thing you\'ve done to get someone\'s number.' },
  { id: 'l3_77', level: 3, tags: ['flirty', 'social'], text: 'If you had to send a thirst trap to one person in this room, who would it be and what would it look like?' },
  { id: 'l3_78', level: 3, tags: ['physical', 'challenge'], text: 'Let someone run an ice cube along your jawline, neck, or collarbone for 10 seconds.' },
  { id: 'l3_79', level: 3, tags: ['embarrassing', 'bold'], text: 'What is the weirdest turn-on you have that most people would find ridiculous?' },
  { id: 'l3_80', level: 3, tags: ['social', 'funny'], text: 'Give everyone in the room a \"sex archetype\" nickname based on vibe (e.g., \"the romantic,\" \"the chaotic one\").' },
];
