import type { Dare } from './types';

export const level5Dares: Dare[] = [
  { id: 'l5_1',  level: 5, tags: ['flirty', 'physical'], text: 'Go into a dark room with the person of your choice for exactly 2 minutes. What happens, happens.' },
  { id: 'l5_2',  level: 5, tags: ['bold', 'challenge'], text: 'Let the group pick two people. Those two people must kiss on the lips for 10 seconds.' },
  { id: 'l5_3',  level: 5, tags: ['physical', 'flirty'], text: 'Remove your underwear without taking off your pants/skirt. Keep it off for the rest of the game.' },
  { id: 'l5_4',  level: 5, tags: ['bold', 'embarrassing'], text: 'Let the group go through the hidden photos album on your phone.' },
  { id: 'l5_5',  level: 5, tags: ['flirty', 'physical'], text: 'Give whoever spun you a hickey or a very visible red mark anywhere on their body.' },
  { id: 'l5_6',  level: 5, tags: ['alcohol', 'flirty'], text: 'Take a shot off someone’s bare chest or lower stomach.' },
  { id: 'l5_7',  level: 5, tags: ['physical', 'bold'], text: 'Take off your shirt and pants. You must play the next 3 rounds in only your underwear.' },
  { id: 'l5_8',  level: 5, tags: ['flirty', 'social'], text: 'Describe in detail your ultimate sexual fantasy involving at least one person in this room.' },
  { id: 'l5_9',  level: 5, tags: ['bold', 'challenge'], text: 'Send a single heart emoji to your ex and don\'t reply to them until tomorrow morning.' },
  { id: 'l5_10', level: 5, tags: ['physical', 'flirty'], text: 'Let the person to your left straddle your lap and make out with you for 15 seconds.' },
  { id: 'l5_11', level: 5, tags: ['embarrassing', 'bold'], text: 'Admit to the most degenerate or morally questionable sexual encounter you\'ve ever had.' },
  { id: 'l5_12', level: 5, tags: ['physical', 'challenge'], text: 'Let someone blindfold you and lightly whip or spank you with a belt or towel 3 times.' },
  { id: 'l5_13', level: 5, tags: ['flirty', 'social'], text: 'If you had to have a threesome with two people in this room, who would they be?' },
  { id: 'l5_14', level: 5, tags: ['bold', 'embarrassing'], text: 'Show everyone the last piece of porn or explicit content you watched or looked at.' },
  { id: 'l5_15', level: 5, tags: ['physical', 'flirty'], text: 'Suck on the finger of the person to your right for 10 seconds while maintaining eye contact.' },
  { id: 'l5_16', level: 5, tags: ['alcohol', 'challenge'], text: 'Waterfall your drink! Someone else starts drinking, you start, and you can\'t stop until they do.' },
  { id: 'l5_17', level: 5, tags: ['flirty', 'bold'], text: 'Admit your deepest kink. Don\'t hold back.' },
  { id: 'l5_18', level: 5, tags: ['physical', 'social'], text: 'Let two people simultaneously kiss your neck for 20 seconds.' },
  { id: 'l5_19', level: 5, tags: ['embarrassing', 'challenge'], text: 'Send a nude (or highly suggestive picture) to a contact chosen by the group.' },
  { id: 'l5_20', level: 5, tags: ['flirty', 'physical'], text: 'Let the group choose a person. You must grind on them for 30 seconds to a song of their choice.' },
  { id: 'l5_21', level: 5, tags: ['bold', 'social'], text: 'Have you ever slept with a married or taken person? Give the details.' },
  { id: 'l5_22', level: 5, tags: ['physical', 'flirty'], text: 'French kiss the person who spun you for 15 seconds.' },
  { id: 'l5_23', level: 5, tags: ['flirty', 'embarrassing'], text: 'Tell the group how many people you have slept with, and what your "record" in one day/weekend is.' },
  { id: 'l5_24', level: 5, tags: ['alcohol', 'bold'], text: 'Everyone who has had a threesome takes a shot. If nobody has, the person reading this takes a shot.' },
  { id: 'l5_25', level: 5, tags: ['flirty', 'physical'], text: 'Let the person across from you put their hand in your pocket or down your pants for 10 seconds.' },
  { id: 'l5_26', level: 5, tags: ['bold', 'social'], text: 'Confess the most illegal thing you\'ve ever done.' },
  { id: 'l5_27', level: 5, tags: ['physical', 'challenge'], text: 'Play 7 Minutes in Heaven with a player chosen by the group. You must go right now.' },
  { id: 'l5_28', level: 5, tags: ['embarrassing', 'bold'], text: 'Admit to a time you accidentally sent an inappropriate text to the wrong person.' },
  { id: 'l5_29', level: 5, tags: ['flirty', 'social'], text: 'Rank the top 3 best lovers you\'ve ever had and explain why they earned their spot.' },
  { id: 'l5_30', level: 5, tags: ['physical', 'flirty'], text: 'Let someone blindfold you and put ice in your underwear.' },
  { id: 'l5_31', level: 5, tags: ['alcohol', 'flirty'], text: 'Drink a shot out of someone\'s mouth (baby-bird style) or the entire group drinks.' },
  { id: 'l5_32', level: 5, tags: ['bold', 'challenge'], text: 'Let the group post a Tinder/Bumble profile for you (or update your current one) and you can’t change it for 24 hours.' },
  { id: 'l5_33', level: 5, tags: ['social', 'embarrassing'], text: 'What is the absolute most humiliating thing that has ever happened to you during sex?' },
  { id: 'l5_34', level: 5, tags: ['physical', 'funny'], text: 'Take off your shirt and let the group slap your chest or back.' },
  { id: 'l5_35', level: 5, tags: ['flirty', 'bold'], text: 'Tell the person to your left exactly how you would undress them.' },
  { id: 'l5_36', level: 5, tags: ['physical', 'challenge'], text: 'Let the person across from you lightly bite or suck on your inner thigh.' },
  { id: 'l5_37', level: 5, tags: ['bold', 'embarrassing'], text: 'Reveal a sexual experience you instantly regretted.' },
  { id: 'l5_38', level: 5, tags: ['flirty', 'social'], text: 'Which two people in this room do you think should hook up?' },
  { id: 'l5_39', level: 5, tags: ['physical', 'flirty'], text: 'Let someone tie your hands behind your back and blindfold you for the next 3 rounds.' },
  { id: 'l5_40', level: 5, tags: ['alcohol', 'bold'], text: 'Finish whatever drink is in your hand immediately. If it\'s empty, take a shot.' },
  { id: 'l5_41', level: 5, tags: ['funny', 'embarrassing'], text: 'Show us the most naked photo of yourself on your phone right now. No exceptions.' },
  { id: 'l5_42', level: 5, tags: ['bold', 'challenge'], text: 'Call your parents and ask them a highly suggestive or inappropriate question.' },
  { id: 'l5_43', level: 5, tags: ['flirty', 'social'], text: 'Who in the room do you think is a secretly dominant freak?' },
  { id: 'l5_44', level: 5, tags: ['physical', 'flirty'], text: 'Let the person to your right sit on your chest or stomach while you lay down for the rest of the round.' },
  { id: 'l5_45', level: 5, tags: ['embarrassing', 'bold'], text: 'Admit if you have ever been caught masturbating. By who?' },
  { id: 'l5_46', level: 5, tags: ['flirty', 'challenge'], text: 'Kiss every player in the session on whatever body part they choose (PG-13 to R depending on their consent).' },
  { id: 'l5_47', level: 5, tags: ['alcohol', 'physical'], text: 'Spill a little bit of alcohol on your stomach and let someone lick it off.' },
  { id: 'l5_48', level: 5, tags: ['bold', 'social'], text: 'What is a completely toxic thought you regularly have but would never act on?' },
  { id: 'l5_49', level: 5, tags: ['flirty', 'embarrassing'], text: 'Detail the weirdest place you’ve ever had sex or hooked up.' },
  { id: 'l5_50', level: 5, tags: ['physical', 'bold'], text: 'Let anyone in the group choke you or grab your neck while maintaining eye contact for 10 seconds.' },
  /* ── Batch 2 — Dares 51–80 ── */
  { id: 'l5_51', level: 5, tags: ['bold', 'flirty'], text: 'Tell the group the most unhinged, graphic fantasy you\'ve ever had — in full detail. No skipping.' },
  { id: 'l5_52', level: 5, tags: ['physical', 'challenge'], text: 'Let the group assign two people to switch one item of clothing with each other right now.' },
  { id: 'l5_53', level: 5, tags: ['flirty', 'social'], text: 'Who in this room would you most want to have a completely secret, no-consequences night with?' },
  { id: 'l5_54', level: 5, tags: ['bold', 'embarrassing'], text: 'Confess the most outrageous lie you\'ve ever told to get someone into bed.' },
  { id: 'l5_55', level: 5, tags: ['physical', 'flirty'], text: 'Let two people slowly remove your shoes and socks and then massage your feet for 60 seconds.' },
  { id: 'l5_56', level: 5, tags: ['alcohol', 'bold'], text: 'Drink if you\'ve ever done something in public that would classify as indecent exposure.' },
  { id: 'l5_57', level: 5, tags: ['bold', 'social'], text: 'What is the most x-rated thing someone has done to you that you absolutely cannot forget?' },
  { id: 'l5_58', level: 5, tags: ['flirty', 'challenge'], text: 'Stand in front of the room and do your most seductive dance for 60 full seconds.' },
  { id: 'l5_59', level: 5, tags: ['physical', 'bold'], text: 'Allow someone to playfully restrain your wrists above your head while you stand against a wall for 10 seconds.' },
  { id: 'l5_60', level: 5, tags: ['alcohol', 'flirty'], text: 'Pour champagne (or any drink) down your chest from your collarbone and dare someone to catch it.' },
  { id: 'l5_61', level: 5, tags: ['embarrassing', 'bold'], text: 'Let someone scroll through your DM requests and read the wildest message you\'ve received.' },
  { id: 'l5_62', level: 5, tags: ['social', 'flirty'], text: 'Which two people in this room should have hooked up already and why haven\'t they yet?' },
  { id: 'l5_63', level: 5, tags: ['physical', 'challenge'], text: 'Lay completely still on the floor while someone traces your body outline with their fingertip for 30 seconds.' },
  { id: 'l5_64', level: 5, tags: ['bold', 'funny'], text: 'Describe exactly what your sex playlist sounds like and play the opener out loud.' },
  { id: 'l5_65', level: 5, tags: ['flirty', 'physical'], text: 'Let the person to your right use only their lips to remove something from your hand or wrist.' },
  { id: 'l5_66', level: 5, tags: ['alcohol', 'challenge'], text: 'Waterfall until the last person standing wins a dare-pass card for next round.' },
  { id: 'l5_67', level: 5, tags: ['bold', 'embarrassing'], text: 'Tell the room about the dirtiest thing you\'ve ever done completely sober. Completely.' },
  { id: 'l5_68', level: 5, tags: ['physical', 'flirty'], text: 'Let someone sit on your face — clothed — for 5 seconds. Both must not move.' },
  { id: 'l5_69', level: 5, tags: ['social', 'bold'], text: 'Who in this room do you think secretly wants to be absolutely devoured?' },
  { id: 'l5_70', level: 5, tags: ['flirty', 'challenge'], text: 'Go into the bathroom, take a photo that is as close to a thirst trap as you legally can, and show everyone.' },
  { id: 'l5_71', level: 5, tags: ['bold', 'social'], text: 'Rank every person in this room by how they would perform under pressure — romantically. Defend each placement.' },
  { id: 'l5_72', level: 5, tags: ['physical', 'funny'], text: 'Let the group choose your sleeping position for the rest of the game. They must vote without you knowing.' },
  { id: 'l5_73', level: 5, tags: ['alcohol', 'bold'], text: 'Pour a shot and make the most attractive person in the room drink it from between your fingers.' },
  { id: 'l5_74', level: 5, tags: ['embarrassing', 'bold'], text: 'Describe your most chaotic, regret-filled one-night stand story without using names.' },
  { id: 'l5_75', level: 5, tags: ['flirty', 'social'], text: 'If the game ended right now and you could spend the night with one person here — who and why?' },
  { id: 'l5_76', level: 5, tags: ['physical', 'challenge'], text: 'Let the group vote on a 15-second physical dare involving two people in the room. No veto allowed.' },
  { id: 'l5_77', level: 5, tags: ['bold', 'funny'], text: 'Describe your ideal morning after in exact, unfiltered detail.' },
  { id: 'l5_78', level: 5, tags: ['flirty', 'embarrassing'], text: 'Which of your exes would the people in this room be most surprised you got with?' },
  { id: 'l5_79', level: 5, tags: ['physical', 'bold'], text: 'Let any volunteer pin you gently against any surface for 8 seconds. No resistance allowed.' },
  { id: 'l5_80', level: 5, tags: ['social', 'bold'], text: 'If everyone in this room had to rate your attractiveness by secret ballot, what do you think your average score would be? Take a vote.' },
];
